server:
  port: 8080


spring:

  datasource:
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.driver
    url: jdbc:mysql://localhost:3306/crudtask?createDatabaseIfNotExist=true

  jpa:
    generate-ddl: true

    hibernate:
      ddl-auto: update

    properties:
      hibernate:
      dialect: MySQLDialect

    show-sql: true
    open-in-view: true



# Pagination settings
  data:
    web:
      pageable:
        default-page-size: 10
        max-page-size: 50
        page-parameter: pageNo
        size-parameter: pageSize
